Standardize fzf-launcher bash variable expansion to always use braces (${VAR}).

diff --git a/.local/bin/fzf-launcher b/.local/bin/fzf-launcher
--- a/.local/bin/fzf-launcher
+++ b/.local/bin/fzf-launcher
@@ -2,7 +2,7 @@
 # vim: set ft=bash tw=88 nu ai et ts=2 sw=2:
 #------------------------------------------------------------------------------
 # User: 00riddle00 (Tomas Giedraitis)
-# Date: 2025-06-17 13:22:02 EEST
+# Date: 2026-08-08 18:08:03 CEST
 # Path: ~/.local/bin/fzf-launcher
 # URL:  https://github.com/00riddle00/dotfiles
 #------------------------------------------------------------------------------
@@ -33,18 +33,18 @@ if ! { exec 0>&3; } 1>/dev/null 2>&1; then
   exec 3>/dev/null # If file descriptor 3 is unused in parent shell, output to /dev/null
 fi
 # shellcheck disable=SC2154
-trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+trap 's=${?}; echo "${0}: Error on line "${LINENO}": ${BASH_COMMAND}"; exit ${s}' ERR
 IFS=$'\n\t'
 DEL=$'\34'
 
 FZF_COMMAND="${FZF_COMMAND:=fzf}"
-TERMINAL_COMMAND="${TERMINAL_COMMAND:="$TERMINAL -e"}"
+TERMINAL_COMMAND="${TERMINAL_COMMAND:="${TERMINAL} -e"}"
 GLYPH_COMMAND="${GLYPH_COMMAND-  }"
 GLYPH_DESKTOP="${GLYPH_DESKTOP-  }"
-CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sway-launcher-desktop"
+CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/sway-launcher-desktop"
 PROVIDERS_FILE="${PROVIDERS_FILE:=providers.conf}"
 if [[ "${PROVIDERS_FILE#/}" == "${PROVIDERS_FILE}" ]]; then
-  # $PROVIDERS_FILE is a relative path, prepend $CONFIG_DIR
+  # ${PROVIDERS_FILE} is a relative path, prepend ${CONFIG_DIR}
   PROVIDERS_FILE="${CONFIG_DIR}/${PROVIDERS_FILE}"
 fi
 if [[ ! -v PREVIEW_WINDOW ]]; then
@@ -72,20 +72,20 @@ if [ -f "${PROVIDERS_FILE}" ]; then
     }
   }' "${PROVIDERS_FILE}")"
   if [[ ! -v HIST_FILE ]]; then
-    HIST_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/${0##*/}-${PROVIDERS_FILE##*/}-history.txt"
+    HIST_FILE="${XDG_CACHE_HOME:-${HOME}/.cache}/${0##*/}-${PROVIDERS_FILE##*/}-history.txt"
   fi
 else
   PROVIDERS['desktop']="${0} list-entries${DEL}${0} describe-desktop \"{1}\"${DEL}${0} run-desktop '{1}' {2}${DEL}test -f '{1}' || exit 43"
   PROVIDERS['command']="${0} list-commands${DEL}${0} describe-command \"{1}\"${DEL}${TERMINAL_COMMAND} {1}${DEL}command -v '{1}' || exit 43"
   if [[ ! -v HIST_FILE ]]; then
-    HIST_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/${0##*/}-history.txt"
+    HIST_FILE="${XDG_CACHE_HOME:-${HOME}/.cache}/${0##*/}-history.txt"
   fi
 fi
 PROVIDERS['user']="exit${DEL}exit${DEL}{1}" # Fallback provider that simply executes the exact command if there were no matches
 
 if [[ -n "${HIST_FILE}" ]]; then
-  mkdir -p "${HIST_FILE%/*}" && touch "$HIST_FILE"
-  readarray HIST_LINES <"$HIST_FILE"
+  mkdir -p "${HIST_FILE%/*}" && touch "${HIST_FILE}"
+  readarray HIST_LINES <"${HIST_FILE}"
 fi
 
 function describe() {
@@ -95,12 +95,12 @@ function describe() {
   [ -n "${PROVIDER_ARGS[1]}" ] && eval "${PROVIDER_ARGS[1]//\{1\}/${2}}"
 }
 function describe-desktop() {
-  description=$(sed -ne '/^Comment=/{s/^Comment=//;p;q}' "$1")
-  echo -e "\033[33m$(sed -ne '/^Name=/{s/^Name=//;p;q}' "$1")\033[0m"
+  description=$(sed -ne '/^Comment=/{s/^Comment=//;p;q}' "${1}")
+  echo -e "\033[33m$(sed -ne '/^Name=/{s/^Name=//;p;q}' "${1}")\033[0m"
   echo "${description:-No description}"
 }
 function describe-command() {
-  readarray arr < <(whatis -l "$1" 2>/dev/null)
+  readarray arr < <(whatis -l "${1}" 2>/dev/null)
   description="${arr[0]}"
   description="${description#* - }"
   echo -e "\033[33m${1}\033[0m"
@@ -109,14 +109,14 @@ function describe-command() {
 
 function provide() {
   # shellcheck disable=SC2086
-  readarray -d ${DEL} -t PROVIDER_ARGS <<<${PROVIDERS[$1]}
+  readarray -d ${DEL} -t PROVIDER_ARGS <<<${PROVIDERS[${1}]}
   eval "${PROVIDER_ARGS[0]}"
 }
 function list-commands() {
-  IFS=: read -ra path <<<"$PATH"
+  IFS=: read -ra path <<<"${PATH}"
   for dir in "${path[@]}"; do
-    printf '%s\n' "$dir/"* |
-      awk -F / -v pre="$GLYPH_COMMAND" '{print $NF "\034command\034\033[31m" pre "\033[0m" $NF;}'
+    printf '%s\n' "${dir}/"* |
+      awk -F / -v pre="${GLYPH_COMMAND}" '{print $NF "\034command\034\033[31m" pre "\033[0m" $NF;}'
   done | sort -u
 }
 function list-entries() {
@@ -125,9 +125,9 @@ function list-entries() {
   IFS=':' read -ra DIRS <<<"${XDG_DATA_HOME-${HOME}/.local/share}:${XDG_DATA_DIRS-/usr/local/share:/usr/share}"
   for i in "${!DIRS[@]}"; do
     if [[ ! -d "${DIRS[i]}" ]]; then
-      unset -v 'DIRS[$i]'
+      unset -v 'DIRS[${i}]'
     else
-      DIRS[$i]="${DIRS[i]}/applications/**/*.desktop"
+      DIRS[${i}]="${DIRS[i]}/applications/**/*.desktop"
     fi
   done
 
@@ -136,7 +136,7 @@ function list-entries() {
 }
 function entries() {
   # shellcheck disable=SC2068
-  awk -v pre="$GLYPH_DESKTOP" -F= '
+  awk -v pre="${GLYPH_DESKTOP}" -F= '
     function desktopFileID(filename){
       sub("^.*applications/", "", filename);
       sub("/", "-", filename);
@@ -183,18 +183,18 @@ function entries() {
                       print FILENAME "\034desktop\034\033[33m" pre name "\033[0m (" actions[i, "name"] ")\034" actions[i, "key"]
       }
     }' \
-    $@ </dev/null
+    ${@} </dev/null
   # the empty stdin is needed in case no *.desktop files
 }
 function run-desktop() {
-  CMD="$("${0}" generate-command "$@" 2>&3)"
+  CMD="$("${0}" generate-command "${@}" 2>&3)"
   echo "Generated Launch command from .desktop file: ${CMD}" >&3
   eval "${CMD}"
 }
 function generate-command() {
   # Define the search pattern that specifies the block to search for within the .desktop file
   PATTERN="^\\\\[Desktop Entry\\\\]"
-  if [[ -n $2 ]]; then
+  if [[ -n ${2} ]]; then
     PATTERN="^\\\\[Desktop Action ${2}\\\\]"
   fi
   echo "Searching for pattern: ${PATTERN}" >&3
@@ -228,18 +228,18 @@ function generate-command() {
       printf "exec "
       if (terminal){ printf terminal_cmd " " }
       print exec
-    }' "$1"
+    }' "${1}"
 }
 
 function shouldAutostart() {
-    local condition="$(cat $1 | rg "AutostartCondition" | cut -d'=' -f2)"
+    local condition="$(cat ${1} | rg "AutostartCondition" | cut -d'=' -f2)"
     local filename="${XDG_CONFIG_HOME-${HOME}/.config}/${condition#* }"
-    case $condition in
+    case ${condition} in
         if-exists*)
-            [[ -e $filename ]]
+            [[ -e ${filename} ]]
             ;;
         unless-exists*)
-            [[ ! -e $filename ]]
+            [[ ! -e ${filename} ]]
             ;;
         *)
             return 0
@@ -249,7 +249,7 @@ function shouldAutostart() {
 
 function autostart() {
   for application in $(list-autostart); do
-      if shouldAutostart "$application" ; then
+      if shouldAutostart "${application}" ; then
           (exec setsid /bin/sh -c "$(run-desktop "${application}")" &>/dev/null &)
       fi
   done
@@ -261,14 +261,14 @@ function list-autostart() {
   IFS=':' read -ra DIRS <<<"${XDG_CONFIG_HOME-${HOME}/.config}:${XDG_CONFIG_DIRS-/etc/xdg}"
   for i in "${!DIRS[@]}"; do
     if [[ ! -d "${DIRS[i]}" ]]; then
-      unset -v 'DIRS[$i]'
+      unset -v 'DIRS[${i}]'
     else
-      DIRS[$i]="${DIRS[i]}/autostart/*.desktop"
+      DIRS[${i}]="${DIRS[i]}/autostart/*.desktop"
     fi
   done
 
   # shellcheck disable=SC2068
-  awk -v pre="$GLYPH_DESKTOP" -F= '
+  awk -v pre="${GLYPH_DESKTOP}" -F= '
     function desktopFileID(filename){
       sub("^.*autostart/", "", filename);
       sub("/", "-", filename);
@@ -307,77 +307,77 @@ purge() {
    readarray -td ${DEL} PROVIDER_ARGS <<<${PROVIDERS[${PROVIDER_NAME}]}
    PURGE_CMD=${PROVIDER_ARGS[3]}
    [ -z "${PURGE_CMD}" ] && PURGE_CMD='test -f "{1}" || exit 43'
-   PURGE_CMDS[$PROVIDER_NAME]="${PURGE_CMD%$'\n'}"
+   PURGE_CMDS[${PROVIDER_NAME}]="${PURGE_CMD%$'\n'}"
   done
   for HIST_LINE in "${HIST_LINES[@]#*' '}"; do
     readarray -td $'\034' HIST_ENTRY <<<${HIST_LINE}
     ENTRY=${HIST_ENTRY[1]}
-    readarray -td ' ' FILTER <<<${PURGE_CMDS[$ENTRY]//\{1\}/${HIST_ENTRY[0]}}
+    readarray -td ' ' FILTER <<<${PURGE_CMDS[${ENTRY}]//\{1\}/${HIST_ENTRY[0]}}
     (eval "${FILTER[@]}" 1>/dev/null) # Run filter command discarding output. We only want the exit status
-    if [[ $? -ne 43 ]]; then
+    if [[ ${?} -ne 43 ]]; then
       echo "1 ${HIST_LINE[@]%$'\n'}" >> "${HIST_FILE}"
     fi
   done
 }
 
-case "$1" in
+case "${1}" in
 describe | describe-desktop | describe-command | entries | list-entries | list-commands | list-autostart | generate-command | autostart | run-desktop | provide | purge)
-  "$@"
+  "${@}"
   exit
   ;;
 esac
 echo "Starting launcher instance with the following providers:" "${!PROVIDERS[@]}" >&3
 
 FZFPIPE=$(mktemp -u)
-mkfifo "$FZFPIPE"
-trap 'rm "$FZFPIPE"' EXIT INT
+mkfifo "${FZFPIPE}"
+trap 'rm "${FZFPIPE}"' EXIT INT
 
 # Append Launcher History, removing usage count
-(printf '%s' "${HIST_LINES[@]#* }" >>"$FZFPIPE") &
+(printf '%s' "${HIST_LINES[@]#* }" >>"${FZFPIPE}") &
 
 # Iterate over providers and run their list-command
 for PROVIDER_NAME in "${!PROVIDERS[@]}"; do
-  (bash -c "${0} provide ${PROVIDER_NAME}" >>"$FZFPIPE") &
+  (bash -c "${0} provide ${PROVIDER_NAME}" >>"${FZFPIPE}") &
 done
 
 readarray -t COMMAND_STR <<<$(
   ${FZF_COMMAND} --ansi +s -x -d '\034' --nth ..3 --with-nth 3 \
     --print-query \
-    --preview "$0 describe {2} {1}" \
+    --preview "${0} describe {2} {1}" \
     --preview-window="${PREVIEW_WINDOW}" \
     --no-multi --cycle \
     --prompt="${GLYPH_PROMPT-# }" \
     --header='' --no-info --margin='1,2' \
     --color='16,gutter:-1' \
-    <"$FZFPIPE"
+    <"${FZFPIPE}"
 ) || exit 1
 # Get the last line of the fzf output. If there were no matches, it contains the query which we'll treat as a custom command
 # If there were matches, it contains the selected item
 COMMAND_STR=$(printf '%s\n' "${COMMAND_STR[@]: -1}")
 # We still need to format the query to conform to our fallback provider.
 # We check for the presence of field separator character to determine if we're dealing with a custom command
-if [[ $COMMAND_STR != *$'\034'* ]]; then
+if [[ ${COMMAND_STR} != *$'\034'* ]]; then
     COMMAND_STR="${COMMAND_STR}"$'\034user\034'"${COMMAND_STR}"$'\034'
     SKIP_HIST=1 # I chose not to include custom commands in the history. If this is a bad idea, open an issue please
 fi
 
-[ -z "$COMMAND_STR" ] && exit 1
+[ -z "${COMMAND_STR}" ] && exit 1
 
-if [[ -n "${HIST_FILE}" && ! "$SKIP_HIST" ]]; then
+if [[ -n "${HIST_FILE}" && ! "${SKIP_HIST}" ]]; then
   # update history
   for i in "${!HIST_LINES[@]}"; do
-    if [[ "${HIST_LINES[i]}" == *" $COMMAND_STR"$'\n' ]]; then
+    if [[ "${HIST_LINES[i]}" == *" ${COMMAND_STR}"$'\n' ]]; then
       HIST_COUNT=${HIST_LINES[i]%% *}
-      HIST_LINES[$i]="$((HIST_COUNT + 1)) $COMMAND_STR"$'\n'
+      HIST_LINES[${i}]="$((HIST_COUNT + 1)) ${COMMAND_STR}"$'\n'
       match=1
       break
     fi
   done
   if ! ((match)); then
-    HIST_LINES+=("1 $COMMAND_STR"$'\n')
+    HIST_LINES+=("1 ${COMMAND_STR}"$'\n')
   fi
 
-  printf '%s' "${HIST_LINES[@]}" | sort -nr >"$HIST_FILE"
+  printf '%s' "${HIST_LINES[@]}" | sort -nr >"${HIST_FILE}"
 fi
 
 # shellcheck disable=SC2086
